version: 2
jobs:
  build:
    working_directory: /go/src/github.com/szyn/mog
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: make deps
      - run: go test -v ./...
    
  deploy:
    working_directory: /go/src/github.com/szyn/mog
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go get -u github.com/tcnksm/ghr
      - run: make cross-build
      - run: make dist
      - run: ghr -delete -t ${GITHUB_TOKEN} -u szyn -r mog --replace $(git describe --tags | perl -anlE 'm/\A([^\-]+)-?/; print $1') dist/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/